spring.application.name=ecommerce-api

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:ecommerce}
spring.datasource.username=${DB_USER:ecommerce}
spring.datasource.password=${DB_PASS:ecommerce}

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:padrao}
